### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by tgonzales** [goodmind/treact-native#1]
macOsX
node v6.9.5
npm  v3.10.10

$ git clone https://github.com/goodmind/treact
$ cd treact
$ npm install
$ npm run build

ts-loader: Using typescript@2.3.3 and /Users/persona/Documents/projetos/tmp/treact/tsconfig.json
Hash: bf1f5d9cf57749fb4d8d
Version: webpack 1.15.0
Time: 13400ms
   [0] multi app 52 bytes {0} [built]
   [0] multi vendor 160 bytes {1} [built]
 [514] ./config/main.js 678 bytes {0} [built]
    + 601 hidden modules

WARNING in ./src/app/redux/store.ts
Error: [12, 7]: Identifier 'middlewares' is never reassigned; use 'const' instead of 'let'.

WARNING in ./src/app/containers/Html/index.tsx
Error: [6, 14]: Don't use 'Object' as a type. Avoid using the `Object` type. Did you mean `object`?

WARNING in ./src/app/helpers/Telegram/Updates/index.ts
Error: [13, 16]: Don't use 'Function' as a type. Avoid using the `Function` type. Prefer a specific function type, like `() => void`.

WARNING in ./src/app/helpers/Telegram/index.ts
Error: [60, 19]: Identifier 'len' is never reassigned; use 'const' instead of 'let'.
[55, 33]: Spaces before function parens are disallowed
[96, 26]: Spaces before function parens are disallowed

WARNING in ./src/app/redux/actions.ts
Error: [3, 13]: Use an interface instead of a type literal.
[10, 13]: Use an interface instead of a type literal.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(6,6): error TS2300: Duplicate identifier 'RequestType'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(8,6): error TS2300: Duplicate identifier 'RequestDestination'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(11,6): error TS2300: Duplicate identifier 'RequestMode'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(12,6): error TS2300: Duplicate identifier 'RequestCredentials'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(13,6): error TS2300: Duplicate identifier 'RequestCache'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(16,6): error TS2300: Duplicate identifier 'RequestRedirect'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(18,6): error TS2300: Duplicate identifier 'ResponseType'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(21,6): error TS2300: Duplicate identifier 'ReferrerPolicy'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(41,6): error TS2300: Duplicate identifier 'HeadersInit'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(43,15): error TS2300: Duplicate identifier 'Headers'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(66,5): error TS2687: All declarations of 'bodyUsed' must have identical modifiers.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(93,6): error TS2300: Duplicate identifier 'BodyInit'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(109,6): error TS2300: Duplicate identifier 'RequestInfo'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(111,15): error TS2300: Duplicate identifier 'Request'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(156,15): error TS2300: Duplicate identifier 'Response'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(180,13): error TS2300: Duplicate identifier 'fetch'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/src/server.tsx
(57,40): error TS2345: Argument of type 'History' is not assignable to parameter of type 'History'.
  Types of property 'createLocation' are incompatible.
    Type '{ (path?: LocationDescriptor, action?: string, key?: string): Location; (path?: string, state?: a...' is not assignable to type '(path?: LocationDescriptor, action?: Action, key?: string) => Location'.
      Type 'Location' is not assignable to type 'Location'. Two different types with this name exist, but they are unrelated.
        Types of property 'action' are incompatible.
          Type 'string' is not assignable to type 'Action'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/src/server.tsx
(59,9): error TS2345: Argument of type '{ history: History & HistoryUnsubscribe; routes: Element; location: any; }' is not assignable to parameter of type 'MatchArgs'.
  Types of property 'history' are incompatible.
    Type 'History & HistoryUnsubscribe' is not assignable to type 'History'.
      Property 'pushState' is missing in type 'History & HistoryUnsubscribe'.

ERROR in ./src/app/redux/store.ts
Module build failed: Error: Compilation failed due to tslint errors.
    at report (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:93:11)
    at lint (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:74:3)
    at Object.module.exports (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:140:3)
 @ ./src/client.tsx 30:14-42

ERROR in ./src/app/containers/Html/index.tsx
Module build failed: Error: Compilation failed due to tslint errors.
    at report (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:93:11)
    at lint (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:74:3)
    at Object.module.exports (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:140:3)
 @ ./src/app/containers/index.tsx 6:13-30

ERROR in ./src/app/helpers/Telegram/Updates/index.ts
Module build failed: Error: Compilation failed due to tslint errors.
    at report (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:93:11)
    at lint (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:74:3)
    at Object.module.exports (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:140:3)
 @ ./src/app/containers/InstantMessages/index.tsx 21:16-51

ERROR in ./src/app/helpers/Telegram/index.ts
Module build failed: Error: Compilation failed due to tslint errors.
    at report (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:93:11)
    at lint (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:74:3)
    at Object.module.exports (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:140:3)
 @ ./src/app/redux/modules/chatList/index.ts 5:17-44

ERROR in ./src/app/redux/actions.ts
Module build failed: Error: Compilation failed due to tslint errors.
    at report (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:93:11)
    at lint (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:74:3)
    at Object.module.exports (/Users/persona/Documents/projetos/tmp/treact/node_modules/tslint-loader/index.js:140:3)
 @ ./src/app/redux/modules/messages/index.ts 8:16-34

> vortigern@0.1.0 postbuild /Users/persona/Documents/projetos/tmp/treact
> webpack --config config/webpack/server.js

ts-loader: Using typescript@2.3.3 and /Users/persona/Documents/projetos/tmp/treact/tsconfig.json
Hash: 1fd64460e3ffd734d1de
Version: webpack 1.15.0
Time: 6453ms
                                      Asset     Size  Chunks             Chunk Names
images/324dafba081ccc78440b090aadf73a82.png   116 kB          [emitted]  
images/8f7aa22d3effc947922ec6a3de4dd472.jpg   266 kB          [emitted]  
images/934e3f64be585a452da5888c61fc3c8b.png  1.86 kB          [emitted]  
images/ff6afebd4b28e4ddb02ecfc449f2342e.png   115 kB          [emitted]  
images/5f2b0bf24db0624d1a775f74108739b8.png   3.4 kB          [emitted]  
                               ../server.js  1.15 MB       0  [emitted]  main
   [1] ./config/main.js 678 bytes {0} [built]
 [354] ./config/webpack/dev.js 3.16 kB {0} [built]
    + 359 hidden modules

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(6,6): error TS2300: Duplicate identifier 'RequestType'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(8,6): error TS2300: Duplicate identifier 'RequestDestination'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(11,6): error TS2300: Duplicate identifier 'RequestMode'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(12,6): error TS2300: Duplicate identifier 'RequestCredentials'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(13,6): error TS2300: Duplicate identifier 'RequestCache'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(16,6): error TS2300: Duplicate identifier 'RequestRedirect'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(18,6): error TS2300: Duplicate identifier 'ResponseType'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(21,6): error TS2300: Duplicate identifier 'ReferrerPolicy'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(41,6): error TS2300: Duplicate identifier 'HeadersInit'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(43,15): error TS2300: Duplicate identifier 'Headers'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(66,5): error TS2687: All declarations of 'bodyUsed' must have identical modifiers.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(93,6): error TS2300: Duplicate identifier 'BodyInit'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(109,6): error TS2300: Duplicate identifier 'RequestInfo'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(111,15): error TS2300: Duplicate identifier 'Request'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(156,15): error TS2300: Duplicate identifier 'Response'.

ERROR in /Users/persona/Documents/projetos/tmp/treact/node_modules/@types/isomorphic-fetch/index.d.ts
(180,13): error TS2300: Duplicate identifier 'fetch'.

ERROR in ./src/server.tsx
(57,40): error TS2345: Argument of type 'History' is not assignable to parameter of type 'History'.
  Types of property 'createLocation' are incompatible.
    Type '{ (path?: LocationDescriptor, action?: string, key?: string): Location; (path?: string, state?: a...' is not assignable to type '(path?: LocationDescriptor, action?: Action, key?: string) => Location'.
      Type 'Location' is not assignable to type 'Location'. Two different types with this name exist, but they are unrelated.
        Types of property 'action' are incompatible.
          Type 'string' is not assignable to type 'Action'.

ERROR in ./src/server.tsx
(59,9): error TS2345: Argument of type '{ history: History & HistoryUnsubscribe; routes: Element; location: any; }' is not assignable to parameter of type 'MatchArgs'.
  Types of property 'history' are incompatible.
    Type 'History & HistoryUnsubscribe' is not assignable to type 'History'.
      Property 'pushState' is missing in type 'History & HistoryUnsubscribe'.

ERROR in ./src/server.tsx
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/manifest.json in /Users/persona/Documents/projetos/tmp/treact/src
 @ ./src/server.tsx 24:15-48

**Comment by goodmind** [comment]
<strike>I abandoned this project until `telegram-mtproto` stabilize</strike>
Oh, I see that you are clone `treact` project not `treact-native`
Well, then you should use `development` branch
